-- Postgres schema for ti-aggregator, translated from backend/db.py
--
-- Translation principles (deliberate, to keep the code diff minimal):
--   1. Table and column names are byte-identical to SQLite. No query text
--      changes are needed for naming reasons.
--   2. Integer boolean flags (triaged, archived, alive, success, ...) stay
--      INTEGER, not BOOLEAN. Every "WHERE archived = 0" and every Python
--      truthiness check keeps working unchanged.
--   3. Timestamp columns stay TEXT, not TIMESTAMPTZ. SQLite CURRENT_TIMESTAMP
--      yields 'YYYY-MM-DD HH:MM:SS' in UTC and the app reads these as strings
--      and serializes them straight to JSON. TIMESTAMPTZ would return datetime
--      objects from psycopg and change the API wire format.
--   4. JSON-bearing columns stay TEXT, not JSONB. The app calls json.loads()
--      on them; JSONB would return dicts and break those call sites. The few
--      SQL-side JSON reads cast explicitly: col::jsonb.
--   5. AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY so the migration can
--      insert explicit ids; sequences are reset after load.
--
-- ALTER-added columns from db.py's idempotent migration lists are folded in.

-- --------------------------------------------------------------- functions --
-- SQLite's date() returns NULL for unparseable input; Postgres raises
-- InvalidDatetimeFormat. RSS feeds frequently omit pubDate, so feed_manager
-- passes an empty string into the dedup comparison. This helper restores the
-- SQLite behaviour so a single malformed date cannot abort a feed poll.
CREATE OR REPLACE FUNCTION try_date(txt text)
RETURNS date
LANGUAGE plpgsql
IMMUTABLE
STRICT
AS $$
BEGIN
    IF btrim(txt) = '' THEN
        RETURN NULL;
    END IF;
    RETURN txt::timestamptz::date;
EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$;

BEGIN;

-- ---------------------------------------------------------------- entries --
CREATE TABLE IF NOT EXISTS entries (
    hash                TEXT PRIMARY KEY,
    source              TEXT NOT NULL,
    title               TEXT,
    link                TEXT,
    published           TEXT,
    summary             TEXT,
    tags                TEXT DEFAULT '{}',
    ingested            TEXT DEFAULT to_char(now() AT TIME ZONE 'utc',
                                             'YYYY-MM-DD HH24:MI:SS'),
    triaged             INTEGER DEFAULT 0,
    severity            TEXT DEFAULT 'Unknown',
    ttps                TEXT DEFAULT '',
    ai_summary          TEXT DEFAULT '',
    archived            INTEGER DEFAULT 0,
    archived_at         TEXT DEFAULT NULL,
    is_duplicate        INTEGER DEFAULT 0,
    canonical_id        TEXT DEFAULT NULL,
    iocs                TEXT DEFAULT '{}',
    kev_flag            INTEGER DEFAULT 0,
    epss_score          DOUBLE PRECISION DEFAULT NULL,
    priority_score      DOUBLE PRECISION DEFAULT NULL,
    enriched            INTEGER DEFAULT 0,
    stack_match         INTEGER DEFAULT 0,
    stack_matched_items TEXT DEFAULT '[]',
    content             TEXT DEFAULT '',
    normalized_title    TEXT DEFAULT NULL,
    group_id            TEXT DEFAULT NULL
);

-- ---------------------------------------------------------------- sources --
CREATE TABLE IF NOT EXISTS sources (
    name  TEXT PRIMARY KEY,
    score INTEGER NOT NULL DEFAULT 50,
    tier  INTEGER NOT NULL DEFAULT 3
);

-- ------------------------------------------------------------ stack_items --
CREATE TABLE IF NOT EXISTS stack_items (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    name     TEXT NOT NULL,
    keywords TEXT NOT NULL
);

-- ------------------------------------------------------------------ users --
CREATE TABLE IF NOT EXISTS users (
    entra_oid    TEXT PRIMARY KEY,
    email        TEXT NOT NULL,
    display_name TEXT NOT NULL,
    role         TEXT NOT NULL CHECK (role IN ('admin', 'viewer')),
    is_active    INTEGER NOT NULL DEFAULT 1,
    created_at   TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc',
                                                'YYYY-MM-DD HH24:MI:SS'),
    updated_at   TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc',
                                                'YYYY-MM-DD HH24:MI:SS')
);

-- ------------------------------------------------------------- ioc_ledger --
CREATE TABLE IF NOT EXISTS ioc_ledger (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type             TEXT NOT NULL,
    subtype          TEXT NOT NULL DEFAULT '',
    value            TEXT NOT NULL,
    first_seen       TEXT NOT NULL,
    last_seen        TEXT NOT NULL,
    occurrence_count INTEGER NOT NULL DEFAULT 1,
    entry_hashes     TEXT NOT NULL DEFAULT '[]',
    benign           INTEGER DEFAULT 0,
    benign_reason    TEXT DEFAULT NULL,
    UNIQUE (type, subtype, value)
);

-- --------------------------------------------------------- runzero_assets --
CREATE TABLE IF NOT EXISTS runzero_assets (
    id             TEXT PRIMARY KEY,
    org            TEXT NOT NULL,
    site           TEXT NOT NULL DEFAULT '',
    hostname       TEXT NOT NULL DEFAULT '',
    os             TEXT NOT NULL DEFAULT '',
    addresses_json TEXT NOT NULL DEFAULT '[]',
    software_json  TEXT NOT NULL DEFAULT '[]',
    alive          INTEGER NOT NULL DEFAULT 1,
    last_seen      BIGINT NOT NULL DEFAULT 0,
    tags_json      TEXT NOT NULL DEFAULT '[]'
);

-- ---------------------------------------------------------- runzero_vulns --
CREATE TABLE IF NOT EXISTS runzero_vulns (
    asset_id  TEXT NOT NULL,
    cve_id    TEXT NOT NULL,
    severity  TEXT NOT NULL DEFAULT '',
    vuln_name TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (asset_id, cve_id)
);

-- -------------------------------------------------------- runzero_matches --
CREATE TABLE IF NOT EXISTS runzero_matches (
    entry_hash   TEXT NOT NULL,
    asset_id     TEXT NOT NULL,
    match_type   TEXT NOT NULL,
    match_detail TEXT NOT NULL DEFAULT '',
    confidence   TEXT NOT NULL,
    PRIMARY KEY (entry_hash, asset_id, match_type)
);

-- ------------------------------------------------------- runzero_sync_log --
CREATE TABLE IF NOT EXISTS runzero_sync_log (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    synced_at   TEXT NOT NULL,
    org_count   INTEGER NOT NULL DEFAULT 0,
    asset_count INTEGER NOT NULL DEFAULT 0,
    vuln_count  INTEGER NOT NULL DEFAULT 0,
    match_count INTEGER NOT NULL DEFAULT 0,
    status      TEXT NOT NULL,
    error       TEXT NOT NULL DEFAULT ''
);

-- --------------------------------------------------------- feed_fetch_log --
CREATE TABLE IF NOT EXISTS feed_fetch_log (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_name     TEXT NOT NULL,
    polled_at     TEXT NOT NULL,
    success       INTEGER NOT NULL DEFAULT 1,
    items_fetched INTEGER NOT NULL DEFAULT 0,
    error_msg     TEXT NOT NULL DEFAULT ''
);

-- ---------------------------------------------------------- exposure_items --
-- Added by the exposure remediation tracking feature.
CREATE TABLE IF NOT EXISTS exposure_items (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id      TEXT NOT NULL,
    entry_hash    TEXT NOT NULL,
    status        TEXT NOT NULL DEFAULT 'active',
    notes         TEXT NOT NULL DEFAULT '',
    assigned_to   TEXT,
    first_seen    TEXT NOT NULL,
    last_seen     TEXT NOT NULL,
    remediated_at TEXT,
    UNIQUE (asset_id, entry_hash)
);

-- ------------------------------------------------------ exposure_audit_log --
CREATE TABLE IF NOT EXISTS exposure_audit_log (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exposure_item_id INTEGER NOT NULL,
    actor            TEXT NOT NULL,
    action           TEXT NOT NULL,
    detail           TEXT NOT NULL DEFAULT '',
    created_at       TEXT NOT NULL
);

-- ---------------------------------------------------------------- indexes --
CREATE INDEX IF NOT EXISTS idx_entries_group
    ON entries (group_id);
CREATE INDEX IF NOT EXISTS idx_entries_source_norm_title
    ON entries (source, normalized_title, published);
CREATE INDEX IF NOT EXISTS idx_entries_active_ingested
    ON entries (archived, is_duplicate, ingested DESC);
CREATE INDEX IF NOT EXISTS idx_entries_source_active_ingested
    ON entries (source, archived, is_duplicate, ingested DESC);
CREATE INDEX IF NOT EXISTS idx_entries_severity_active_ingested
    ON entries (severity, archived, is_duplicate, ingested DESC);
CREATE INDEX IF NOT EXISTS idx_entries_triage_queue
    ON entries (triaged, archived, ingested ASC);
CREATE INDEX IF NOT EXISTS idx_entries_retriage
    ON entries (triaged, archived, is_duplicate, ingested DESC);
CREATE INDEX IF NOT EXISTS idx_entries_failed_triage
    ON entries (triaged, severity, archived, is_duplicate, ingested DESC);
CREATE INDEX IF NOT EXISTS idx_ioc_ledger_type
    ON ioc_ledger (type);
CREATE INDEX IF NOT EXISTS idx_ioc_ledger_last_seen
    ON ioc_ledger (last_seen);
CREATE INDEX IF NOT EXISTS idx_sources_tier_score_name
    ON sources (tier ASC, score DESC, name ASC);
CREATE INDEX IF NOT EXISTS idx_runzero_vulns_cve
    ON runzero_vulns (cve_id);
CREATE INDEX IF NOT EXISTS idx_runzero_matches_hash
    ON runzero_matches (entry_hash);
CREATE INDEX IF NOT EXISTS idx_runzero_matches_confidence
    ON runzero_matches (confidence);
CREATE INDEX IF NOT EXISTS idx_feed_fetch_log_name
    ON feed_fetch_log (feed_name, polled_at DESC);
CREATE INDEX IF NOT EXISTS idx_exp_items_status
    ON exposure_items (status, asset_id);
CREATE INDEX IF NOT EXISTS idx_exp_audit_item
    ON exposure_audit_log (exposure_item_id, created_at DESC);

COMMIT;
